Repository qri-io/starlib, pull requests merged in 2021-09, with the labels that each got.

#106 fix(dataframe): Getting columns won't segfault if none exist
  dataframe/dataframe.go
  dataframe/dataframe_test.go
  dataframe/testdata/dataframe_columns_none.expect.txt
  dataframe/testdata/dataframe_columns_none.star
Labels: fix

#105 feat(dataframe): Select rows from a dataframe using a bool series
  dataframe/convert.go
  dataframe/dataframe.go
  dataframe/dataframe_test.go
  dataframe/series.go
  dataframe/series_test.go
  dataframe/test_runner_test.go
  dataframe/testdata/dataframe_bool_select.expect.txt
  dataframe/testdata/dataframe_bool_select.star
  dataframe/testdata/dataframe_bool_select_failure.star
  dataframe/testdata/series_attrs.expect.txt
  dataframe/testdata/series_bool_select.expect.txt
  dataframe/testdata/series_bool_select.star
Labels: fix

#107 feat(dataframe): parse_csv to parse csv from text
  dataframe/dataframe.go
  dataframe/dataframe_test.go
  dataframe/testdata/dataframe_head.star
  dataframe/testdata/dataframe_read_csv.star
Labels: feat

#109 feat(dataframe): Multiple str methods, add to series, bool selection
  dataframe/dataframe.go
  dataframe/dataframe_test.go
  dataframe/groupby_result.go
  dataframe/index.go
  dataframe/row_iter.go
  dataframe/series.go
  dataframe/string_methods.go
  dataframe/testdata/dataframe_select_bad_length.star
  dataframe/testdata/dataframe_series_str_select.expect.txt
  dataframe/testdata/dataframe_series_str_select.star
  dataframe/testdata/series_attrs.expect.txt
Labels: feat

#112 feat(dataframe): Unique method, can add new column from list
  dataframe/dataframe.go
  dataframe/series.go
  dataframe/series_test.go
  dataframe/testdata/dataframe_columns.expect.txt
  dataframe/testdata/dataframe_columns.star
  dataframe/testdata/series_attrs.expect.txt
  dataframe/testdata/series_unique.expect.txt
  dataframe/testdata/series_unique.star
Labels: feat

#122 run misspell & a number of other meta-linters in CI
  .github/workflows/golangci-lint.yml
  bsoup/bsoup.go
  bsoup/doc.go
  dataframe/at_indexer.go
  dataframe/convert.go
  dataframe/dataframe.go
  dataframe/doc.go
  dataframe/row_iter.go
  dataframe/series.go
  encoding/csv/csv.go
  encoding/json/doc.go
  geo/geo.go
  hash/hash.go
  http/http.go
  http/http_test.go
  makefile
  util/util_test.go
  xlsx/xlsx.go
Labels: test, chore

#124 feat(dataframe): Stringify limits size, omit extra rows and columns
  dataframe/convert.go
  dataframe/dataframe.go
  dataframe/dataframe_all_methods.go
  dataframe/dataframe_test.go
  dataframe/doc.go
  dataframe/stringify.go
  dataframe/testdata/dataframe_drop.expect.txt
  dataframe/testdata/dataframe_drop.star
  dataframe/testdata/dataframe_stringify.expect.txt
  dataframe/testdata/dataframe_stringify.star
  html/html.go
Labels: feat

#123 docs(math): add examples for math.floor, math.pow
  math/doc.go
Labels: docs

#126 add examples for geo.Point and geo.parseGeoJSON
  geo/doc.go
  geo/geo.go
  geo/geojson.go
Labels: docs
